### PR TITLE
a i18N try

### PR DESCRIPTION
**Pull request by Gaorion**
a test 4 i18n

### CODE REVIEW

**Comment by skybber** [comment]
There are conflicts in fchart3 as I renamed `fcharti18n.py` to `fchart3`. If you don't know how to fix it, I'll look into it tomorrow.

**Comment by skybber** [comment]
Thanks for contribution! Did you try online fchart version at www.czsky.eu?

**Comment by Gaorion** [comment]
>Thanks for contribution! 
okay 
i have to deal now with de help cmd line argument
and i'm looking for some collegue in  my association 
https://www.guyaneastronomie.fr
to help with the translation (po files)

>Did you try online fchart version at [www.czsky.eu](http://www.czsky.eu/)?
yes of course !!!
it's amazing !

**Comment by skybber** [comment]
May be www.deepl.com would be enough.

**Pull request merged**
