### PR TITLE
Gaorion patch 1

### PR DESCRIPTION
**Pull request by Gaorion**

### CODE REVIEW

**Comment by skybber** [comment]
Is there any problem to use i18n stuff in fchart3 bin, it seems that it will be hard to synchronize code in both files in the future.

**Comment by Gaorion** [comment]
maybe i misunderstood
but fchart3i18n.py will be fchart3 
( in github preferred not replace it )
Babel dont scan fchart3 because it dont have the extension .py  

so
1 rename 
   fchart3 in fchart3.py
2 scan with babel
   pybabel extract . -o locale/base.pot
   pybabel update -i locale/base.pot -d locale
   pybabel compile -d locale
3 remove the extension .py
4  install

This afternoon i finished to scan all the code for replacement of  print() by print (_( )) 
and i find this solution 4 the widget 
LABELi18N = {
    'h': _('h'),
    'm':_('m'),
    's':_('s'),
    'G':_('Galaxy'),
    'OCL':_('Open cluster'),
    'GCL':_('Globular cluster'),
    'AST':_('Asterism'),
    'PN':_('Planetary nebula'),
    'N': _('Diffuse nebula'),
    'SNR':_('Supernova remnant'),
    'PG':_('Part of galaxy')
}

**Comment by skybber** [comment]
So I've renamed fchart3i18n.py to fchart3+fixed problems (missing brackets)

**Comment by Gaorion** [comment]
okay !

I finished the work but i use a environment variable to set the language
it's more simple to pass var into modules
a nother option could be .env (Python-dotenv)
but you already   have "Configuration system"

**Comment by skybber** [comment]
If I understand you correctly, there could be priority of sources from which the actual language ID is loaded. For example from lowest to highest:
1. system lang
2. .env
4. enviroment variable
5. configuration file

**Comment by Gaorion** [comment]
-  system lang
   complexe for transalation and exotic language like fr :)
-  .env
   best idea
   to my point 
-  enviroment variable
   un pis-aller
   french get a word 4 for "a  none efficient idea but the only you get"
-  configuration file
   but .env ... 
   and i get a trouble importig module with gettext
   we have to set the lang before any import 
   i  get into trouble why it 
   it's why  i choose a variable environement

**Pull request merged**
